# --- Dimensions in mm ---
HEAD_JOINT_LENGTH = 10
BED_JOINT_HEIGHT = 12.5
BRICK_HEIGHT = 50
BRICK_LENGTH = 210
HALF_BRICK_LENGTH = (BRICK_LENGTH - HEAD_JOINT_LENGTH) // 2
QUARTER_BRICK_LENGTH = (BRICK_LENGTH - HEAD_JOINT_LENGTH * 3) // 4
THREE_QUARTER_BRICK_LENGTH = BRICK_LENGTH - QUARTER_BRICK_LENGTH - HEAD_JOINT_LENGTH

if __name__ == "__main__":
    print(f"BRICK_LENGTH: {BRICK_LENGTH} mm")
    print(f"HALF_BRICK_LENGTH: {HALF_BRICK_LENGTH} mm")
    print(f"HEAD_JOINT_LENGTH: {HEAD_JOINT_LENGTH} mm")
    print(f"QUARTER_BRICK_LENGTH: {QUARTER_BRICK_LENGTH} mm")
